services:
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            target: app_prod
        env_file:
            -   .env.docker.prod
        environment:
            APP_ENV: prod
            APP_DEBUG: 0
            APP_SECRET: ${APP_SECRET}
        depends_on:
            - postgres
            - redis

    nginx:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        ports:
            - "80:80"
        depends_on:
            - php

    postgres:
        image: postgres:18-alpine
        env_file:
            - .env.docker.prod
        volumes:
            - db_data:/var/lib/postgresql

    redis:
        image: redis:alpine
        volumes:
            - redis_data:/data

volumes:
    db_data:
    redis_data:
