version: '3.8'

services:
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            target: app_prod
        environment:
            DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?serverVersion=18&charset=utf8&host=postgres"
            REDIS_URL: "redis://redis:6379"
            APP_ENV: prod
            APP_DEBUG: 0
            APP_SECRET: ${APP_SECRET}
        depends_on:
            - postgres
            - redis

    nginx:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        ports:
            - "80:80"
        depends_on:
            - php

    postgres:
        image: postgres:18-alpine
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
            - db_data:/var/lib/postgresql

    redis:
        image: redis:alpine
        volumes:
            - redis_data:/data

volumes:
    db_data:
    redis_data:
